name: Weedoo Weekly Automation

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Atualizado para a versão mais estável do Python no Node 24

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar Automação e Enviar E-mail
        env:
          EMAIL_REMETENTE: ${{ secrets.EMAIL_REMETENTE }}
          EMAIL_SENHA: ${{ secrets.EMAIL_SENHA }}
          EMAIL_DESTINATARIO: ${{ secrets.EMAIL_DESTINATARIO }}
        run: python script.py
